import './bootstrap';
import '../assets/bootstrap/dist/css/bootstrap.min.css';
import '../assets/font-awesome/css/font-awesome.min.css';
import '../assets/nprogress/nprogress.css';
import '../assets/iCheck/skins/flat/green.css';
import '../assets/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css';
import '../assets/jqvmap/dist/jqvmap.min.css';
import '../assets/bootstrap-daterangepicker/daterangepicker.css';
import '../assets/custom.min.css';
